// Generated by CoffeeScript 1.4.0
(function() {
  var Something;

  Something = (function() {

    function Something(name) {
      this.name = name != null ? name : 'something';
    }

    Something.prototype.toString = function() {
      return this.name;
    };

    return Something;

  })();

  document.addEventListener('DOMContentLoaded', function() {
    var something, something2;
    something = new Something('Beaver');
    something2 = new Something;
    return console.log("" + something + " " + something2);
  }, false);

}).call(this);
